### PR TITLE
[#73607174] locksmithctl: Support for multiple endpoints

### LINKED ISSUE #53: allow for configuration of a list of etcd servers
I have a desire to segment my etcd cluster such that I _only_ run etcd servers on a fixed set of hosts, omitting it from all other hosts on the cluster.

This works great for fleet, as it appears that it allows for a multi-valued list configuration via cloud-config:

    coreos:
        fleet:
            etcd-servers: 1.2.3.4:7001,6.7.8.9:7001

Which renders as:

    $ cat /var/run/systemd/system/fleet.service.d/20-cloudinit.conf 
    [Service]
    Environment="FLEET_ETCD_SERVERS=1.2.3.4:7001,6.7.8.9:7001"

It would be cool if I could configure something similar for locksmithd.  Currently it appears that the best I can achieve is:

    LOCKSMITHD_ENDPOINT=1.2.3.4:7001

But from skimming the code I believe that this will not work if it includes commas.

Bonus points if this was added as a default cloud-config setting under "coreos.locksmith.etcd-servers"

### PR DESCRIPTION
**Pull request by mattbostock**
Support multiple etcd endpoints to be specified either using commandline
flags or an environment variable.

Maintains the `-endpoint` flag for backwards compatibility. Using
commandline flags, specify `-endpoint=<url>` for each endpoint or
pass a comma-delimited list of endpoints, e.g. `-endpoint=<url>,<url>`.
The former syntax is preferable IMO as it makes more sense semantically
given that `-endpoint` is singular rather than plural.

Specifying multiple endpoints using an environment variable is supported
by passing a comma-delimited list, e.g.
`LOCKSMITHCTL_ENDPOINT=<url>,<url>`.

The default endpoint of `http://127.0.0.1:4001` is retained and prints
correctly when `globalFlagset.Usage()` is called. I used `VisitAll()` to
set the default value so that I could make this distinct to the actual
flag value, which `flag.FlagSet.Var()` doesn't support.

The pattern of using a custom flag type that satisfies the `flag.Value`
interface is borrowed from example 3 of the Go Flag tests:
https://golang.org/src/flag/example_test.go

Fixes #53

* * *

Also, rename `globalFlagset` to `globalFlagSet` for consistency with the
`flag.FlagSet` struct in the Go Flag package:
http://golang.org/pkg/flag/#FlagSet

### CODE REVIEW

**Comment by mattbostock** [comment]
_bump_ Is there anything I can do to help get this reviewed/merged?

**Comment by marineam** [comment]
@jonboulle could you review this please since @crawford is out?

File: locksmithctl/locksmithctl.go [hunk 1]
```diff
@@ -82,20 +96,25 @@ type Command struct {
...
 		flags = append(flags, f)
 	})
 	return
 }
 
 func main() {
-	globalFlagset.Parse(os.Args[1:])
-	var args = globalFlagset.Args()
+	globalFlagSet.Parse(os.Args[1:])
+	globalFlagSet.VisitAll(func(f *flag.Flag) {
```
Comment (jonboulle) [inline locksmithctl/locksmithctl.go]: This seems awkward; how about just setting this to the desired value in the `globalFlags` initialisation instead?

**Comment by jonboulle** [comment]
The approach seems like a good compromise to me. Thanks for the patch! Just one comment.

**Comment by mattbostock** [comment]
I've rebased to amend;

I refactored out the `VisitAll()` function which was setting the default endpoint; instead I've set defined default endpoint as constant and set it [here](https://github.com/mattbostock/locksmith/commit/68eb542cdd33f2d6bf71cbb87fc367dac26607c5?diff=unified#diff-d713ec8c4f7b249df26db9c602fa9bfaR56) and [here](https://github.com/mattbostock/locksmith/commit/68eb542cdd33f2d6bf71cbb87fc367dac26607c5?diff=unified#diff-d713ec8c4f7b249df26db9c602fa9bfaR119) such that it appears in the CLI usage message and is explicitly passed to the etcd client library.

IMHO it's preferable to explicitly determine the default endpoint so that the usage message always matches what the etcd client library will actually use; otherwise the client library could change and the usage message would be incorrect. I'm open to suggestions though, as we could remove lines 119-122 if we don't explicitly set the default and rely on the library default.

**Comment by jonboulle** [comment]
@mattbostock That reasoning makes sense.

I would still rather set the default value during init() so we can remove the magic from String(), what do you think about that?

**Comment by mattbostock** [comment]
I'm not keen on the magic in `String()` either, though don't think there is a way to set the default during `init()` because `globalFlags.Endpoints` is a custom flag type.

The `Var()` [method](http://golang.org/pkg/flag/#FlagSet.Var) does not allow you to specify a default separate to the actual value; the default is set to whatever `value` argument is passed to `Var()`. Because `globalFlags.Endpoints` is a slice, any value passed in via `Var()` would be appended to the slice; we then have no way of knowing if the first member of the array is the default or has been passed in using a flag.

**Comment by jonboulle** [comment]
@mattbostock sorry for the delays, locksmith notifications keep talking through the cracks :-(

What I meant was assigning a specific value to global flags.Endpoints, won't that work? Since the var should still refer to the pointer.

**Comment by mattbostock** [comment]
No problem.

If the default value was assigned to `globalFlags.Endpoints` slice, any endpoints passed in explicitly by the user would be appended to that default. So you'd always have `http://127.0.0.1:4001` as an endpoint. Does that answer your question?

**Comment by jonboulle** [comment]
Duh, yes, I was totally not thinking about that. Thanks.

**Comment by mattbostock** [comment]
Could you please push a new release including this change? Thanks!

**Comment by crawford** [comment]
Just tagged 0.2.3. Sorry for the delay.

**Comment by mattbostock** [comment]
@crawford Great, thanks!
