### PR TITLE
 locksmithd: ignore nil sent by dbus.Signal 

### LINKED ISSUE #1987: locksmithd: panic on shutdown
As seen from the shutdown logs of an AWS instance running CL alpha-1432.0.0 (locksmith 0.4.2):
```
May 31 14:06:11 ip-172-31-0-51 systemd[1]: Stopping D-Bus System Message Bus...
May 31 14:06:11 ip-172-31-0-51 locksmithd[668]: panic: runtime error: invalid memory address or nil pointer dereference
May 31 14:06:11 ip-172-31-0-51 locksmithd[668]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x5cb376]
May 31 14:06:11 ip-172-31-0-51 locksmithd[668]: goroutine 16 [running]:
May 31 14:06:11 ip-172-31-0-51 locksmithd[668]: panic(0x91bb00, 0xc42000c060)
May 31 14:06:11 ip-172-31-0-51 locksmithd[668]:         /usr/lib/go1.7/src/runtime/panic.go:500 +0x1a1
May 31 14:06:11 ip-172-31-0-51 locksmithd[668]: github.com/coreos/locksmith/updateengine.(*Client).RebootNeededSignal(0xc4200bfcc0, 0xc42000ea20, 0xc42000e4e0)
May 31 14:06:11 ip-172-31-0-51 locksmithd[668]:         /build/amd64-usr/var/tmp/portage/app-admin/locksmith-0.4.2/work/gopath/src/github.com/coreos/locksmith/updateengine/client.go:83 +0x116
May 31 14:06:11 ip-172-31-0-51 locksmithd[668]: created by main.runDaemon
May 31 14:06:11 ip-172-31-0-51 locksmithd[668]:         /build/amd64-usr/var/tmp/portage/app-admin/locksmith-0.4.2/work/gopath/src/github.com/coreos/locksmith/locksmithctl/daemon.go:388 +0x67d
```

### PR DESCRIPTION
**Pull request by rfairley**
Specifies the loop in RebootNeededSignal to continue if a 'nil' signal is
sent to the client channel connected to the D-Bus. This avoids
dereferencing a nil datatype in NewStatus, which causes the panic in
coreos/bugs#1987.

fixes coreos/bugs#1987

### CODE REVIEW

File: updateengine/client.go [hunk 1]
```diff
@@ -63,7 +63,7 @@ func New() (c *Client, err error) {
 		return nil, err
 	}
 
-	c.object = c.conn.Object("com.coreos.update1", dbus.ObjectPath(dbusPath))
+	c.object = c.conn.Object("com.coreos.update1", dbus.ObjectPath(dbusPath)).(*dbus.Object)
```
Comment (rfairley) [inline updateengine/client.go]: Checked on my machine and this seems to be the line breaking the build - will edit tomorrow.

File: updateengine/status.go [hunk 2]
```diff
@@ -42,6 +42,32 @@ func NewStatus(body []interface{}) (s Status) {
...
 }
 
+func IsSignalStatus(body []interface{}) (isStatus bool) {
+	if len(body) < 5 {
+		return false
+	}
+
+	// Check that elements of body have correct type corresponding to type Status
+	typeIsCorrect := false
+	for i, elem := range body {
```
Comment (lucab) [inline updateengine/status.go]: This code is somewhat awkward. I would suggest instead to move the nil+length+types checking directly into a fallible constructor (e.g. `TryNewStatus` or similar), as this file is the only consumer.
It would look like `TryNewStatus(*dbus.Signal) (Status, error)` so that you can `continue` on error in the loop above.

File: updateengine/client.go (hunk 1 above)
Comment (lucab) [reply updateengine/client.go]: If you think this related to different go toolchain version, feel free to add 1.9.x and 1.10.x to travis. Please note that locksmith relies on an old vendored copy of go-dbus for this, so double-check your environment and dependency resolution first.

Comment (lucab) [reply updateengine/client.go]: If you think this related to different go toolchain versions, feel free to add 1.9.x and 1.10.x to travis. Please note that locksmith relies on an old vendored copy of go-dbus for this, so double-check your environment and dependency resolution first.

File: updateengine/status.go (hunk 2 above)
Comment (rfairley) [reply updateengine/status.go]: I see - makes sense to make use of `error`. Will work on this now. Thank you!

File: updateengine/status.go [hunk 3]
```diff
@@ -28,6 +31,56 @@ type Status struct {
 	NewSize          int64
 }
 
+var (
+	errStatusNil    = errors.New("dbus signal is nil")
+	errStatusLength = errors.New("signal body has insufficient length")
+	errStatusType   = errors.New("signal body has incorrect type")
+	statusZero      = Status{0, 0, "", "", 0}
```
Comment (lucab) [inline updateengine/status.go]: No need for this here. You can either move it to be local to the function, or even better just `return Status{}, errFoo`.

Comment (rfairley) [reply updateengine/status.go]: Made an edit - how's this?

**Comment by rfairley** [comment]
Done! Please let me know if there is anything else. Otherwise, I think it is good to merge.

**Review by lucab — APPROVED** [review]

File: updateengine/status.go [hunk 4]
```diff
@@ -28,6 +31,55 @@ type Status struct {
...
+	errStatusLength = errors.New("signal body has insufficient length")
+	errStatusType   = errors.New("signal body has incorrect type")
+)
+
+// TryNewStatus attempts to create a new Status from a list of fields in
+// the dbus.Signal. An error is returned if the signal is nil, has less fields
+// than required, or has a field of incorrect type (types must be int64, float64,
+// string, string, int64 respectively). If successful, the new status is returned.
+func TryNewStatus(signal *dbus.Signal) (Status, error) {
+
```
Comment (arithx) [inline updateengine/status.go]: extra line break

File: updateengine/status.go [hunk 5]
```diff
@@ -28,6 +31,55 @@ type Status struct {
 	NewSize          int64
 }
 
+var (
+	errStatusNil    = errors.New("dbus signal is nil")
+	errStatusLength = errors.New("signal body has insufficient length")
+	errStatusType   = errors.New("signal body has incorrect type")
```
Comment (arithx) [inline updateengine/status.go]: @lucab: do you think it would be worthwhile to format this error with the failing field?

Comment (lucab) [reply updateengine/status.go]: At the moment it is not really used, so probably not. If we need to surface that somewhere later, we can quickly do there.

File: updateengine/status.go (hunk 4 above)
Comment (rfairley) [reply updateengine/status.go]: Fixing that, thanks!

File: updateengine/status.go (hunk 5 above)
Comment (rfairley) [reply updateengine/status.go]: Will leave it for now. Would the failing field look something like `locksmith: error message here`?

Comment (lucab) [reply updateengine/status.go]: @rfairley it would be something like `fmt.Errorf("signal field %q has incorrect type", fieldname)` in `TryNewStatus` type checks.

Comment (rfairley) [reply updateengine/status.go]: Right, I see. I think it can be left without specifying the field - I agree it can be resurfaced quickly if the need comes up.

**Review by arithx — APPROVED** [review]
Kola run through DO looks good.

File: updateengine/client_test.go [hunk 6]
```diff
@@ -93,6 +93,20 @@ func TestRebootNeededSignal(t *testing.T) {
 		t.Fatal("RebootNeededSignal stopped prematurely")
 	}
 
+	c.ch <- nil
+
+	time.Sleep(10 * time.Millisecond)
+
+	select {
+	case stat := <-r:
```
Comment (ajeddeloh) [inline updateengine/client_test.go]: Do we want to log anything here? Otherwise the error is just eaten?

Comment (rfairley) [reply updateengine/client_test.go]: Is this logging for the test only? It would better to log something for the test case of sending the `nil` signal. (right now `"some other ignored signal"` gets a status printed for it when running `go test` in locksmith/updateengine).

I agree on not logging `RebootNeededSignal` in the case that the loop `continue`s as this would pollute the shutdown logs. Logging one time only if `continue` happens by means of a counter or flag in the `for` loop would be OK though since `nil` signals don't always happen, and it might be useful to know from the shutdown logs if it did. We could add giving one log message for the first failure of `TryNewStatus` in, WDYT?

On logging for the test (in `client_test.go` a log should be added to indicate that the `nil` signal test is happening. I can add this in a bit.

Comment (ajeddeloh) [reply updateengine/client_test.go]: sgtm, and yeah I meant to comment on the continue in the code, not on this test.

**Review by ajeddeloh — APPROVED** [review]
LGTM

File: updateengine/client_test.go (hunk 6 above)
Comment (rfairley) [reply updateengine/client_test.go]: Sounds good, thanks.

On `client_test.go`: Had a second thought (from my comment above) on logging in `client_test.go`, and it is OK as it is since `t.Fatal` is called in case of failure on the `nil` signal test. So `client_test.go` will be kept as in this PR, unless there is anything else to add.

On `RebootNeededSignal`: We can still add a log for the first failure only (so logging the failure happens only once) of `TryNewStatus` in `RebootNeededSignal`, if we want to log *something* for the `nil` signal showing without polluting logs. However it may just be adding unnecessary logic to the code.

If all is good as the PR is now, I think it is OK to merge.

**Comment by lucab** [comment]
@ajeddeloh @arithx fine to merge then?

**Comment by ajeddeloh** [comment]
good to merge (idk if you have merge access?)

**Comment by rfairley** [comment]
Good to merge.

**Comment by lucab** [comment]
@rfairley we need to cut a release with this fix and then forward it to ContainerLinux. Would you mind preparing a PR for the 0.6.2 release? It should pretty much look like this (with a relevant changelog entry): https://github.com/coreos/locksmith/pull/134

**Comment by rfairley** [comment]
@lucab Done - opened PR #138
